[package]
name = "bevy_test_helper_macro_impl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = { version = "1.0.37" }
syn = { version = "2.0.90", features = ["parsing", "full"] }